# Generated by Django 5.0.3 on 2024-03-21 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacao', '0002_cadastroobras_obrasusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorObras',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('deletado', models.BooleanField(default=False)),
                ('fornecedores', models.ManyToManyField(to='qualificacao.cadastrofornecedores')),
                ('obra', models.ManyToManyField(to='qualificacao.cadastroobras')),
            ],
        ),
    ]
