# Generated by Django 5.0.3 on 2024-03-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacao', '0003_fornecedorobras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedorobras',
            name='obra',
        ),
        migrations.AddField(
            model_name='fornecedorobras',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='qualificacao.cadastroobras'),
        ),
    ]
