# Generated by Django 5.0.3 on 2024-03-26 15:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacao', '0004_remove_fornecedorobras_obra_fornecedorobras_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFornecimento',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo_fornecimento', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('deletado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='obrasusuario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='obrasusuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obrasusuario',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obrasusuario',
            name='deletado_em',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
