# Generated by Django 5.0.3 on 2024-04-06 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacao', '0005_tipofornecimento_obrasusuario_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificacaoDetalhes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nf_bms', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('deletado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_1', models.FloatField(default=-1)),
                ('question_2', models.FloatField(default=-1)),
                ('question_3', models.FloatField(default=-1)),
                ('question_4', models.FloatField(default=-1)),
                ('question_5', models.FloatField(default=-1)),
                ('question_6', models.FloatField(default=-1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('deletado', models.BooleanField(default=False)),
                ('tipo_fornecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualificacao.tipofornecimento')),
                ('detalhes_qualificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_qualificacao', to='qualificacao.qualificacaodetalhes')),
            ],
        ),
    ]
