# Generated by Django 5.0.3 on 2024-04-08 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacao', '0008_remove_qualificacao_fornecedor_obra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrasusuario',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='obrasusuario',
            name='auth_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
