# Generated by Django 5.0.3 on 2024-05-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacao', '0009_remove_obrasusuario_auth_user_obrasusuario_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedorobras',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='qualificacao.cadastroobras', unique=True),
        ),
    ]
